### ISSUE TITLE
Error while executing "example_async.c"

### ISSUE THREAD

**Issue by rohitist** [mapr/libhbase#6]
Below is the log while running `example_async.c` :

```
2015-01-06 17:22:31,710 INFO  6201(0x7f3714ba2720)@example_async.c(ensureTable#354): Creating table 'TempTable'...
2015-01-06 17:22:32,147 INFO  6201(0x7f3714ba2720)@example_async.c(ensureTable#356): Table 'TempTable' created, verifying if enabled.
2015-01-06 17:22:32,185 INFO  6201(0x7f3714ba2720)@example_async.c(ensureTable#359): Table 'TempTable' is enabled, result 0.
2015-01-06 17:22:33,559 INFO  6201(0x7f3714ba2720)@example_async.c(ensureTable#362): Attempted to disable table 'TempTable', result 0.
2015-01-06 17:22:33,584 ERROR 6201(0x7f3714ba2720)@jnihelper.cc(ParseJavaException#438): Java exception: org.apache.hadoop.hbase.TableNotEnabledException
        org.apache.hadoop.hbase.TableNotEnabledException: TempTable
        at org.apache.hadoop.hbase.master.handler.DisableTableHandler.prepare(DisableTableHandler.java:100)
        at org.apache.hadoop.hbase.master.HMaster.disableTable(HMaster.java:1969)
        at org.apache.hadoop.hbase.master.HMaster.disableTable(HMaster.java:1980)
        at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:40466)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2027)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:108)
        at org.apache.hadoop.hbase.ipc.FifoRpcScheduler$1.run(FifoRpcScheduler.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

2015-01-06 17:22:33,584 WARN  6201(0x7f3714ba2720)@hbase_admin.cc(DisableTable#352): DisableTable() called for 'TempTable' which is already disabled.
2015-01-06 17:22:33,584 INFO  6201(0x7f3714ba2720)@example_async.c(ensureTable#365): Attempted to disable table 'TempTable' again, result 0.
2015-01-06 17:22:33,792 INFO  6201(0x7f3714ba2720)@example_async.c(ensureTable#368): Attempted to enable table 'TempTable', result 0.
2015-01-06 17:22:33,817 ERROR 6201(0x7f3714ba2720)@jnihelper.cc(ParseJavaException#438): Java exception: org.apache.hadoop.hbase.TableNotDisabledException
        org.apache.hadoop.hbase.TableNotDisabledException: TempTable
        at org.apache.hadoop.hbase.master.handler.EnableTableHandler.prepare(EnableTableHandler.java:111)
        at org.apache.hadoop.hbase.master.HMaster.enableTable(HMaster.java:1944)
        at org.apache.hadoop.hbase.master.HMaster.enableTable(HMaster.java:1955)
        at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:40464)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2027)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:108)
        at org.apache.hadoop.hbase.ipc.FifoRpcScheduler$1.run(FifoRpcScheduler.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

2015-01-06 17:22:33,817 WARN  6201(0x7f3714ba2720)@hbase_admin.cc(EnableTable#332): EnableTable() called for 'TempTable' which is already enabled.
2015-01-06 17:22:33,817 INFO  6201(0x7f3714ba2720)@example_async.c(ensureTable#371): Attempted to enable table 'TempTable' again, result 0.
2015-01-06 17:22:33,925 INFO  6201(0x7f3714ba2720)@example_async.c(main#432): Connecting to HBase cluster using Zookeeper ensemble 'localhost:2181'.
2015-01-06 17:22:33,817 WARN  6201(0x7f3714ba2720)@hbase_admin.cc(EnableTable#332): EnableTable() called for 'TempTable' which is already enabled.
2015-01-06 17:22:33,817 INFO  6201(0x7f3714ba2720)@example_async.c(ensureTable#371): Attempted to enable table 'TempTable' again, result 0.
2015-01-06 17:22:33,925 INFO  6201(0x7f3714ba2720)@example_async.c(main#432): Connecting to HBase cluster using Zookeeper ensemble 'localhost:2181'.
2015-01-06 17:22:33,925 ERROR 6201(0x7f3714ba2720)@jnihelper.cc(GetClassReference#283): Unable to get class id for class 'org/apache/hadoop/hbase/jni/ClientProxy'
2015-01-06 17:22:33,926 ERROR 6201(0x7f3714ba2720)@jnihelper.cc(GetClassReference#283): Unable to get class id for class 'org/apache/hadoop/hbase/jni/PutProxy'
2015-01-06 17:22:33,927 ERROR 6201(0x7f3714ba2720)@jnihelper.cc(GetClassReference#283): Unable to get class id for class 'org/apache/hadoop/hbase/jni/RowProxy'
2015-01-06 17:22:33,927 ERROR 6201(0x7f3714ba2720)@jnihelper.cc(GetClassReference#283): Unable to get class id for class 'org/apache/hadoop/hbase/jni/MutationProxy'
2015-01-06 17:22:33,927 ERROR 6201(0x7f3714ba2720)@jnihelper.cc(GetClassReference#283): Unable to get class id for class 'org/apache/hadoop/hbase/jni/MutationProxy'
2015-01-06 17:22:33,928 ERROR 6201(0x7f3714ba2720)@jnihelper.cc(GetClassReference#283): Unable to get class id for class 'org/apache/hadoop/hbase/jni/MutationProxy'
2015-01-06 17:22:33,928 INFO  6201(0x7f3714ba2720)@example_async.c(main#467): Sending row with row key : 'row00'.
```

**SAME ERROR FOR EACH ROW**

```
2015-01-06 17:22:33,951 INFO  6201(0x7f3714ba2720)@example_async.c(main#467): Sending row with row key : 'row09'.
2015-01-06 17:22:33,952 ERROR 6201(0x7f3714ba2720)@jnihelper.cc(GetClassReference#283): Unable to get class id for class 'org/apache/hadoop/hbase/jni/ClientProxy'
2015-01-06 17:22:33,952 ERROR 6201(0x7f3714ba2720)@jnihelper.cc(GetClassReference#283): Unable to get class id for class 'org/apache/hadoop/hbase/jni/ClientProxy'
2015-01-06 17:22:33,952 INFO  6201(0x7f3714ba2720)@example_async.c(wait_for_flush#139): Waiting for flush to complete.
```

**AND THE EXAMPLE CODE FREEZES HERE**

I want to integrate `libhbase` into a tool of mine and that tool is a long-lived process. So, I want to make sure `libhbase` is a reliable library to work with. So, please help to fix these errors.

**Comment by mkmoisen** [comment]
@rohitist Were you ever able to find a solution?
